Add a page to Export Artists
TheUltimateC0der/Deemix.Autoloader pull request #18
Opened 2021-02-03 22:11 UTC by humor4fun

2021-02-03 22:31 UTC, TheUltimateC0der requested changes
You also forgot to add the corresponding action to the corresponding controller

2021-02-03 22:31 UTC, TheUltimateC0der commented on Deemixrr/Views/Artist/Export.cshtml
> +									 @foreach (var artist in Model.Artists)
It would be a lot easier to just use string.join()

2021-02-03 22:31 UTC, TheUltimateC0der commented on Deemixrr/Views/Artist/Export.cshtml
> +									 @foreach (var artist in Model.Artists)
It would be a lot easier to just use string.join()

2021-02-03 22:31 UTC, TheUltimateC0der commented on Deemixrr/Views/Artist/Export.cshtml
> +									 @foreach (var artist in Model.Artists)
It would be a lot easier to just use string.join()

2021-02-04 14:33 UTC, humor4fun reviewed
changed the viewmodel

2021-02-04 14:44 UTC, closed without merging

2021-02-04 14:45 UTC, humor4fun commented
Missing a few components of the required changes. I'll send a new PR for you that includes those.